name: Test

on:
  # schedule:
  #   - cron: '0 0 1 * *'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Slack Notification on SUCCESS
        if: success()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "text": "Test Notfication",
              "channel": "CBYR49SFP",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.head_commit.message }}"
                  }
                }
              ]
            }